### ISSUE TITLE
About Semaphore Type 

### ISSUE THREAD

**Issue by frankdevhub** [frankdevhub/Coding-Laboratory#2]
@KonH @MaoJianwei 

Q: As follows the result that printed shown  as the "mark" for the thread should be different , however it shown the same , did anyone know why ? thanks . The result is that:
Current Thread begin:	1518189277956
Current Thread begin:	1518189277956
Current Thread end:	1518189277956
Current Thread end:	1518189277956
Current Thread begin:	1518189277956
Current Thread end:	1518189277956

`package io.github.frankdevhub.core.chp1;

import java.util.concurrent.Semaphore;

public class SemaphoreSynMulit {
	

	protected class SharedResource {
		protected Semaphore sph = new Semaphore(1);
	}

	protected class AbstractThread extends Thread {

		protected SharedResource resource;

		protected AbstractThread(SharedResource resource) {
			this.resource = resource;
		}

		/**
		 * @return the resource
		 */
		public SharedResource getResource() {
			return resource;
		}

		@Override
		public void run() {
			try {
				Long mark = System.currentTimeMillis();
				resource.sph.acquire(1);
				System.out.println("Current Thread begin:\t" + mark);
				Thread.sleep(1000);
				resource.sph.release(1);
				System.out.println("Current Thread end:\t" + mark);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}
	}

	public static void main(String[] args) {
		SemaphoreSynMulit synMulti =new SemaphoreSynMulit();
		SharedResource resource = synMulti.new SharedResource();
		SemaphoreSynMulit.AbstractThread testThread1 = synMulti.new AbstractThread(resource);
		SemaphoreSynMulit.AbstractThread testThread2 = synMulti.new AbstractThread(resource);
		SemaphoreSynMulit.AbstractThread testThread3 = synMulti.new AbstractThread(resource);
		testThread1.start();
		testThread2.start();
		testThread3.start();
	}
}
`

**Comment by MaoJianwei** [comment]
You did not change the "mark" variable

At 2018-02-09 23:29:02, "Frank Heisenberg" <notifications@github.com> wrote:


@KonH@MaoJianwei

Q: As follows the result that printed shown as the "mark" for the thread should be different , however it shown the same , did anyone know why ? thanks . The result is that:
Current Thread begin: 1518189277956
Current Thread begin: 1518189277956
Current Thread end: 1518189277956
Current Thread end: 1518189277956
Current Thread begin: 1518189277956
Current Thread end: 1518189277956

`package io.github.frankdevhub.core.chp1;

import java.util.concurrent.Semaphore;

public class SemaphoreSynMulit {

protected class SharedResource {
	protected Semaphore sph = new Semaphore(1);
}

protected class AbstractThread extends Thread {

	protected SharedResource resource;

	protected AbstractThread(SharedResource resource) {
		this.resource = resource;
	}

	/**
	 * @return the resource
	 */
	public SharedResource getResource() {
		return resource;
	}

	@Override
	public void run() {
		try {
			Long mark = System.currentTimeMillis();
			resource.sph.acquire(1);
			System.out.println("Current Thread begin:\t" + mark);
			Thread.sleep(1000);
			resource.sph.release(1);
			System.out.println("Current Thread end:\t" + mark);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}
}

public static void main(String[] args) {
	SemaphoreSynMulit synMulti =new SemaphoreSynMulit();
	SharedResource resource = synMulti.new SharedResource();
	SemaphoreSynMulit.AbstractThread testThread1 = synMulti.new AbstractThread(resource);
	SemaphoreSynMulit.AbstractThread testThread2 = synMulti.new AbstractThread(resource);
	SemaphoreSynMulit.AbstractThread testThread3 = synMulti.new AbstractThread(resource);
	testThread1.start();
	testThread2.start();
	testThread3.start();
}


}
`

**Comment by frankdevhub** [comment]
Thanks Mao
@MaoJianwei
